controllers/CertificateController.php
<?php

namespace app\controllers;

use app\helpers\AuthHelper;
use app\models\ars\ClientCertificate;
use app\models\ars\Course;
use app\models\ars\CourseAdditionalFieldClientCertificate;
use app\models\ars\Middlemen;
use app\models\searches\CertificateSearch;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * CertificateController implements the CRUD actions for ClientCertificate model.
 */
class CertificateController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['change-number'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_EDIT_CERTIFICATE_NUMBER,
                    ],
                    [
                        'actions' => ['set-status'],
                        'allow'   => true,
                        'roles'   => array_merge(AuthHelper::CAN_EDIT_CERTIFICATE_PAID, AuthHelper::CAN_EDIT_CERTIFICATE_PRINTED, AuthHelper::CAN_EDIT_CERTIFICATE_ISSUED),
                    ],
                    [
                        'actions' => ['set-middlemen', 'set-additional-data'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_EDIT_CERTIFICATE_ADDITIONAL_DATA,
                    ],
                    [
                        'actions' => ['set-date-of-issue'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_EDIT_CERTIFICATE_ISSUED,
                    ],
                    [
                        'actions' => ['index', 'view'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_SEE_MENU_CERTIFICATES,
                    ],
                    [
                        'actions' => ['list-by-middlemen'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_SEE_MENU_REPORT,
                    ],
                    [
                        'actions' => ['create', 'update', 'add', 'set-group', 'delete', 'set-additional-field'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_EDIT_CERTIFICATE,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionChangeNumber()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $id = Yii::$app->request->get('id');
            $number = Yii::$app->request->get('number');

            $certificate = ClientCertificate::findOne($id);

            $certificate->number = $number;

            if ($certificate->save()) {
                return ['status' => 'OK'];
            }

            return ['status' => 'Error', 'messages' => $certificate->getErrors()];
        }
    }

    public function actionSetAdditionalData()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $id = Yii::$app->request->get('id');
            $attribute = Yii::$app->request->get('attribute');
            $value = Yii::$app->request->get('value');

            $certificate = ClientCertificate::findOne($id);

            $certificate->$attribute = $value;

            if ($certificate->save()) {
                return ['status' => 'OK', 'additionalSum' => $certificate->additional_sum, 'totalSum' => $certificate->total_sum, 'costPrice' => $certificate->priceCost()];
            }

            return ['status' => 'Error', 'messages' => $certificate->getErrors()];
        }
    }

    public function actionSetStatus()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $id = Yii::$app->request->get('id');
            $attribute = Yii::$app->request->get('attribute');
            $value = Yii::$app->request->get('value');

            $certificate = ClientCertificate::findOne($id);

            $certificate->$attribute = $value;

            if ($certificate->save()) {
                return ['status' => 'OK'];
            }

            return ['status' => 'Error', 'messages' => $certificate->getErrors()];
        }
    }

    public function actionSetGroup()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $certificateId = Yii::$app->request->get('certificate_id');
            $groupId = Yii::$app->request->get('group_id');

            $certificate = ClientCertificate::findOne($certificateId);

            $certificate->group_id = $groupId;

            if ($certificate->save()) {
                return ['status' => 'OK'];
            }

            return ['status' => 'Error', 'messages' => $certificate->getErrors()];
        }
    }

    public function actionSetDateOfIssue()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $id = Yii::$app->request->get('id');
            $value = Yii::$app->request->get('value');

            $certificate = ClientCertificate::findOne($id);

            $certificate->date_of_issue = $value;

            if ($certificate->save()) {
                return ['status' => 'OK'];
            }

            return ['status' => 'Error', 'messages' => $certificate->getErrors()];
        }
    }

    public function actionSetMiddlemen()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $id = Yii::$app->request->get('id');
            $value = Yii::$app->request->get('value');

            $certificate = ClientCertificate::findOne($id);

            $certificate->middlemen_id = $value;

            if ($certificate->save()) {
                return ['status' => 'OK'];
            }

            return ['status' => 'Error', 'messages' => $certificate->getErrors()];
        }
    }

    public function actionSetAdditionalField()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $certificateId = Yii::$app->request->post('certificate_id');
            $additionalFieldId = Yii::$app->request->post('additional_field_id');
            $value = Yii::$app->request->post('value') == 'true';

            if ($value) {
                $certificate = new CourseAdditionalFieldClientCertificate();

                $certificate->client_certificate_id = $certificateId;
                $certificate->course_additional_field_id = $additionalFieldId;
                $certificate->value = '1';

                if ($certificate->save()) {
                    return ['status' => 'OK'];
                }

                return ['status' => 'Error', 'messages' => $certificate->getErrors()];
            } else {
                $certificate = CourseAdditionalFieldClientCertificate::findOne(['course_additional_field_id' => $additionalFieldId, 'client_certificate_id' => $certificateId]);

                if ($certificate->delete()) {
                    return ['status' => 'OK'];
                }

                return ['status' => 'Error', 'messages' => $certificate->getErrors()];
            }
        }
    }

    /**
     * Lists all ClientCertificate models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CertificateSearch();
        $a = Yii::$app->request->queryParams;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionListByMiddlemen()
    {
        $middlemenId = Yii::$app->request->get('middlemen_id');

        $query = ClientCertificate::find();
        if ($middlemenId) {
            $query = $query->where(['middlemen_id' => $middlemenId]);
        }

        $dataProvider = $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $middlemen = Middlemen::findOne($middlemenId);

        return $this->render('list-by', [
            'middlemen' => $middlemen,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ClientCertificate model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the ClientCertificate model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ClientCertificate the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ClientCertificate::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new ClientCertificate model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $models = Course::find()->all();

        if (Yii::$app->request->post('Certificate') && Yii::$app->request->get('client_id')) {

controllers/ClientController.php
<?php

namespace app\controllers;

use app\helpers\AuthHelper;
use app\models\ars\Client;
use app\models\ars\ClientCertificate;
use app\models\ars\Middlemen;
use app\models\forms\UploadForm;
use app\models\searches\ClientSearch;
use app\services\LogService;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_SEE_MENU_CLIENTS,
                    ],
                    [
                        'actions' => ['create', 'update'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_EDIT_CLIENT,
                    ],
                    [
                        'actions' => ['set-comment'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_EDIT_CLIENT_COMMENT,
                    ],
                ],
            ],
        ];
    }
    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $query = ClientCertificate::find()->where(['client_id' => $id])->orderBy(['id' => SORT_DESC]);

        return $this->render('view', [
            'model'                   => $this->findModel($id),
            'certificates'            => $query->all(),
            'middlemens'              => ArrayHelper::map(Middlemen::find()->all(), 'id', 'name'),
        ]);
    }

    /**
     * Finds the Client model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Client the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Client::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new Client model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Client();

        $file = new UploadForm();
        $file->photo = UploadedFile::getInstance($file, 'photo');

        $fileExtension = $file->getExtension();
        if ($fileExtension) {
            $model->photo_dir = 'images/client-photos';
            $model->photo_name = time() . '.' . $file->getExtension();

            $file->upload($model->photo_name, $model->photo_dir);
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if (empty($model->errors) && empty($file->errors)) {
                LogService::add($model, Yii::$app->user->getIdentity());
                $model->save();
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'file' => $file
        ]);
    }

    /**
     * Updates an existing Client model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $file = new UploadForm();
        $file->photo = UploadedFile::getInstance($file, 'photo');

        $fileExtension = $file->getExtension();
        if ($fileExtension) {
            $model->photo_dir = 'images/client-photos';
            $model->photo_name = time() . '.' . $file->getExtension();

            $file->upload($model->photo_name, $model->photo_dir);
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if (empty($model->errors) && empty($file->errors)) {
                LogService::add($model, Yii::$app->user->getIdentity());
                $model->save();

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'file' => $file
        ]);
    }

    public function actionSetComment()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $id = Yii::$app->request->get('id');
            $value = Yii::$app->request->get('value');

            $certificate = Client::findOne($id);

            $certificate->comment = $value;

            if ($certificate->save()) {
                return ['status' => 'OK'];
            }

            return ['status' => 'Error', 'messages' => $certificate->getErrors()];
        }
    }
}

views/client/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\searches\ClientSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="client-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name_ukr') ?>

    <?= $form->field($model, 'patronymic_ukr') ?>

    <?= $form->field($model, 'surname_ukr') ?>

    <?= $form->field($model, 'name_transliteration') ?>

    <?php // echo $form->field($model, 'patronymic_transliteration') ?>

    <?php // echo $form->field($model, 'surname_transliteration') ?>

    <?php // echo $form->field($model, 'birthday') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'email') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/client/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ars\Client */

$this->title = 'Добавление клиента';
$this->params['breadcrumbs'][] = ['label' => 'Клиенты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'file' => $file
    ]) ?>

</div>

views/client/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ars\Client */

$this->title = 'Редактирование клиента: ' . $model->surname_ukr;
$this->params['breadcrumbs'][] = ['label' => 'Клиенты', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="client-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'file' => $file
    ]) ?>

</div>

views/client/view2.php
<?php

use app\helpers\AuthHelper;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\YiiAsset;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\ars\Client */
/* @var $certificate app\models\ars\ClientCertificate */
/* @var $middlemens array */

$i = 0;
$this->title = $model->surname_ukr . ' ' . $model->name_ukr;
$this->params['breadcrumbs'][] = ['label' => 'Клиенты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
YiiAsset::register($this);
?>
<div class="client-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Список', ['index'], ['class' => 'btn btn-success']) ?>
        <?= AuthHelper::canEditCertificate() ? Html::a('Добавить сертификаты', ['/certificate/create?client_id=' . $model->id], ['class' => 'btn btn-info']) : '' ?>
        <?= AuthHelper::canEditClient() ? Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) : '' ?>
    </p>

    <?= DetailView::widget([
        'model'      => $model,
        'attributes' => [
            'name_ukr',
            'patronymic_ukr',
            'surname_ukr',
            'name_transliteration',
            'surname_transliteration',
            'birthday:date',
            'phone',
            'email:email',
            'passport_series',
            'passport_number',
            'passport_date_issued',
            'passport_issued_by',
            'registration_address',
            'inn',
            [
                'attribute' => 'comment',
                'format'    => 'raw',
                'value'     => AuthHelper::CAN_EDIT_CLIENT_COMMENT ? Html::textarea('comment', $model->comment, ['class' => 'form-control comment', 'data-id' => $model->id]) : $model->comment,
            ],
        ],
    ]) ?>

    <p>
        <?= AuthHelper::canPrintPersonalCard() ? Html::button(
            'Персональная карта',
            ['class' => 'btn btn-dark personal-card', 'data-client_id' => $model->id]
        ) : '' ?>
        <?= AuthHelper::canPrintStatementAgreementOffer() ? Html::button(
            'Заявление, соглашение, оферта',
            ['class' => 'btn btn-info act-of-work', 'data-client_id' => $model->id]
        ) : '' ?>
        <?= AuthHelper::canPrintPaymentInvoiceActOfWork() ? Html::button(
            'Счет на оплату и акт работ',
            ['class' => 'btn btn-success payment-invoice', 'data-client_id' => $model->id]
        ) : '' ?>
    </p>
    <?php if (isset($certificates)): ?>
        <?php Pjax::begin(['id' => 'certificates-table']); ?>
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th></th>
                <th>Курс</th>
                <th>Группа</th>
                <th>Клиент</th>
                <th>Доп поля</th>
                <th>Номер</th>
                <?php if (AuthHelper::canEditCertificate()): ?>
                    <th>Дата добавления</th>
                <?php endif; ?>
                <th>Даты обучения</th>
                <th>Прайс, грн</th>
                <?php if (AuthHelper::canSeeCertificateAdditionalData()): ?>
                    <th>Добавочная цена, грн</th>
                    <th>Добавочная цена, %</th>
                    <th>Переплата, грн.</th>
                    <th>Сумма, грн</th>
                <?php endif; ?>
                <th>Оплачен</th>
                <th>Распечатан</th>
                <th>Выдан</th>
                <?php if (AuthHelper::canEditCertificateIssued()): ?>
                    <th>Дата получения</th>
                <?php endif; ?>
                <?php if (AuthHelper::canSeeCertificateAdditionalData()): ?>
                    <th>Посредник</th>
                <?php endif; ?>
                <?php if (AuthHelper::canPrintCertificate()): ?>
                    <th></th>
                <?php endif; ?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($certificates as $certificate): ?>
                <tr data-certificate-id="<?= $certificate->id ?>">
                    <td><?= Html::checkbox('certificate', false, ['class' => 'form-control certificate-check', 'data-id' => $certificate->id]) ?></td>
                    <td><?= ++$i ?></td>
                    <td><?= $certificate->course->title_ukr ?></td>
                    <td><?= AuthHelper::canEditCertificate() && $certificate->group_id ? $certificate->group->name : Html::dropDownList('certificate[' . $certificate->id . ']', false, $certificate->course->getAvailableGroups(), ['prompt' => 'Не выбрано', 'class' => 'form-control change-group', 'data-id' => $certificate->id]) ?></td>
                    <td><?= $certificate->client->getFullNameUkr(true) ?></td>
                    <?php if (AuthHelper::canEditCertificate()): ?>
                        <td>
                            <?php if (count($certificate->course->courseAdditionalFields)): ?>
                                <?= Html::button('Доп. поля', ['class' => "btn btn-primary", 'data-toggle' => "collapse", 'data-target' => "#collapseExample" . $certificate->id, 'aria-expanded' => "false", 'aria-controls' => "collapseExample"]) ?>
                            <?php endif; ?>
                        </td>
                    <?php endif; ?>
                    <td><?= AuthHelper::canEditCertificateNumber() && empty($certificate->number) ? Html::input('text', 'certificateSerialNumber', null, ['class' => 'form-control certificateSerialNumber', 'data-id' => $certificate->id]) : $certificate->number ?></td>
                    <td><?= Yii::$app->formatter->asDate($certificate->date_add) ?></td>
                    <td><?= isset($certificate->group) ? Yii::$app->formatter->asDate($certificate->group->start_date) . ' - ' . Yii::$app->formatter->asDate($certificate->group->end_date) : null ?></td>
                    <td><?= $certificate->cost_price ?></td>
                    <?php if (AuthHelper::canSeeCertificateAdditionalData()): ?>
                        <td class="additional_sum"><?= $certificate->additional_sum ?></td>
                        <td><?= Html::dropDownList('additional_sum_percent', $certificate->additional_sum_percent, array_combine(range(0, 120, 5), range(0, 120, 5)), ['class' => 'form-control additional-sum-percent', 'data-id' => $certificate->id, 'data-attr' => 'additional_sum_percent']) ?></td>
                        <td><?= AuthHelper::canEditCertificateAdditionalData() ? Html::textInput('overpayment', $certificate->overpayment, ['class' => 'form-control overpayment', 'data-id' => $certificate->id, 'data-attr' => 'overpayment']) : $certificate->overpayment ?></td>
                        <td class="total_sum"><?= $certificate->total_sum ?></td>
                    <?php endif; ?>
                    <td><?= Html::checkbox('paid', $certificate->paid, ['class' => 'form-control ajax-status', 'data-id' => $certificate->id, 'data-attribute' => 'paid',] + (AuthHelper::canEditCertificatePaid() ? [] : ['disabled' => 'disabled'])) ?></td>
                    <td><?= Html::checkbox('printed', $certificate->printed, ['class' => 'form-control ajax-status', 'data-id' => $certificate->id, 'data-attribute' => 'printed',] + (AuthHelper::canEditCertificatePrinted() ? [] : ['disabled' => 'disabled'])) ?></td>
                    <td><?= Html::checkbox('issued', $certificate->issued, ['class' => 'form-control ajax-status', 'data-id' => $certificate->id, 'data-attribute' => 'issued',] + (AuthHelper::canEditCertificateIssued() ? [] : ['disabled' => 'disabled'])) ?></td>

                    <?php if (AuthHelper::canEditCertificateIssued()): ?>
                        <td>
                            <?= DatePicker::widget(
                                [
                                    'name'          => 'date_of_issue',
                                    'options'       => ['placeholder' => 'ГГГГ-ММ-ДД', 'autocomplete' => 'off', 'class' => 'date-of-issue', 'data-certificate_id' => $certificate->id],
                                    'type'          => DatePicker::TYPE_INPUT,
                                    'value'         => $certificate->date_of_issue,
                                    'pluginOptions' => [
                                        'autoclose' => true,
                                        'format'    => 'yyyy-mm-dd',
                                    ],
                                    'pluginEvents'  => [
                                        "changeDate" => "function(e) {
                                            let id = $(this).attr('data-certificate_id');
                                            let value = $(this).val();
                                    
                                            $.ajax({
                                                url: '/certificate/set-date-of-issue',
                                                method: 'get',
                                                data: {id: id, value: value},
                                                dataType: 'json',
                                                success: function (response) {
                                                    if (response.status != 'OK') {
                                                        alert('Не удалось сохранить данные. Попробуйте снова');
                                                    }
                                                }
                                            })
                                        }",
                                    ],
                                ]) ?>
                        </td>
                    <?php endif; ?>
                    <?php if (AuthHelper::canSeeCertificateAdditionalData()): ?>
                        <td><?= Html::dropDownList('middlemen', $certificate->middlemen_id, $middlemens, ['class' => 'form-control middlemen', 'data-id' => $certificate->id, 'prompt' => '...']) ?></td>
                    <?php endif; ?>
                    <?php if (AuthHelper::canPrintCertificate()): ?>
                        <td><?= Html::a('Печать',
                                ['print/certificate'], [
                                    'class'       => 'print-button btn btn-success ' . ($certificate->paid ? '' : 'hide'),
                                    'target'      => '_blank',
                                    'data-id'     => $certificate->id,
                                    'data-method' => 'POST',
                                    'data-params' => [
                                        'certificate_id' => $certificate->id,
                                        'csrf_param'     => Yii::$app->request->csrfParam,
                                        'csrf_token'     => Yii::$app->request->csrfToken,
                                    ],
                                ]) ?>
                            <?php if ($certificate->course->has_ukr_only): ?>
                            <?= Html::a('Печать укр. шаблона',
                                ['print/certificate'], [
                                    'class'       => 'print-button btn btn-info ' . ($certificate->paid ? '' : 'hide'),
                                    'target'      => '_blank',
                                    'data-id'     => $certificate->id,
                                    'data-method' => 'POST',
                                    'data-params' => [
                                        'certificate_id' => $certificate->id,
                                        'ukr_only' => 1,
                                        'csrf_param'     => Yii::$app->request->csrfParam,
                                        'csrf_token'     => Yii::$app->request->csrfToken,
                                    ],
                                ]) ?>
                            <?php endif; ?>
                        </td>
                    <?php endif; ?>
                </tr>
                <?php if (count($certificate->course->courseAdditionalFields)): ?>
                    <tr class="collapse" id="collapseExample<?= $certificate->id ?>">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td colspan="7">
                            <div>
                                <div class="additional_fields">
                                    <?php foreach ($certificate->course->courseAdditionalFields as $additionalField): ?>
                                        <p>
                                            <label><?= Html::checkbox('additionalField', in_array($additionalField->id, ArrayHelper::getColumn($certificate->courseAdditionalFields, 'id')), ['class' => 'additionalField', 'data-certificate_id' => $certificate->id, 'data-additional_field_id' => $additionalField->id]) . $additionalField->name ?></label>
                                        </p>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php Pjax::end(); ?>

        <?php $this->registerJsFile('js/certificate.js', ['depends' => ['yii\web\JqueryAsset']]); ?>
        <?php $this->registerJsFile('js/user.js', ['depends' => ['yii\web\JqueryAsset']]); ?>
    <?php endif; ?>
</div>