controllers/ClientController.php
<?php

namespace app\controllers;

use app\helpers\AuthHelper;
use app\models\ars\Client;
use app\models\ars\ClientCertificate;
use app\models\ars\Middlemen;
use app\models\forms\UploadForm;
use app\models\searches\ClientSearch;
use app\services\LogService;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_SEE_MENU_CLIENTS,
                    ],
                    [
                        'actions' => ['create', 'update'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_EDIT_CLIENT,
                    ],
                    [
                        'actions' => ['set-comment'],
                        'allow'   => true,
                        'roles'   => AuthHelper::CAN_EDIT_CLIENT_COMMENT,
                    ],
                ],
            ],
        ];
    }
    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $query = ClientCertificate::find()->where(['client_id' => $id])->orderBy(['id' => SORT_DESC]);

        return $this->render('view', [
            'model'                   => $this->findModel($id),
            'certificates'            => $query->all(),
            'middlemens'              => ArrayHelper::map(Middlemen::find()->all(), 'id', 'name'),
        ]);
    }

    /**
     * Finds the Client model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Client the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Client::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new Client model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Client();

        $file = new UploadForm();
        $file->photo = UploadedFile::getInstance($file, 'photo');

        $fileExtension = $file->getExtension();
        if ($fileExtension) {
            $model->photo_dir = 'images/client-photos';
            $model->photo_name = time() . '.' . $file->getExtension();

            $file->upload($model->photo_name, $model->photo_dir);
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if (empty($model->errors) && empty($file->errors)) {
                LogService::add($model, Yii::$app->user->getIdentity());
                $model->save();
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'file' => $file
        ]);
    }

    /**
     * Updates an existing Client model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $file = new UploadForm();
        $file->photo = UploadedFile::getInstance($file, 'photo');

        $fileExtension = $file->getExtension();
        if ($fileExtension) {
            $model->photo_dir = 'images/client-photos';
            $model->photo_name = time() . '.' . $file->getExtension();

            $file->upload($model->photo_name, $model->photo_dir);
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if (empty($model->errors) && empty($file->errors)) {
                LogService::add($model, Yii::$app->user->getIdentity());
                $model->save();

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'file' => $file
        ]);
    }

    public function actionSetComment()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $id = Yii::$app->request->get('id');
            $value = Yii::$app->request->get('value');

            $certificate = Client::findOne($id);

            $certificate->comment = $value;

            if ($certificate->save()) {
                return ['status' => 'OK'];
            }

            return ['status' => 'Error', 'messages' => $certificate->getErrors()];
        }
    }
}

controllers/ReportController.php
<?php


namespace app\controllers;


use app\helpers\AuthHelper;
use app\models\ars\Client;
use app\models\ars\ClientCertificate;
use app\models\ars\Course;
use app\models\ars\Group;
use app\services\ReportService;
use PhpOffice\PhpSpreadsheet\Writer\Xls;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

class ReportController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['by-dates', 'by-day', 'by-middlemen', 'statistic', 'statistic-by-course'],
                        'allow' => true,
                        'roles' => AuthHelper::CAN_SEE_MENU_REPORT,
                    ],
                    [
                        'actions' => ['print-certificates'],
                        'allow' => true,
                        'roles' => AuthHelper::CAN_PRINT_CERTIFICATE,
                    ],
                ],
            ],
        ];
    }

    public function actionByDates()
    {
        $startDate = Yii::$app->request->post('start_date');
        $endDate = Yii::$app->request->post('end_date');
        $toXls = Yii::$app->request->post('to_xls');

        $data = [];
        $statistics = [];

        if (!empty($startDate)) {
            $data = ClientCertificate::find()
                ->leftJoin(Group::tableName(), 'group_id=group.id')
                ->where(['>=', 'group.end_date', $startDate])
                ->andWhere(['<=', 'group.end_date', $endDate])
                ->all();

            $statistics['totalSum'] = ClientCertificate::find()
                ->leftJoin(Group::tableName(), 'group_id=group.id')
                ->where(['>=', 'group.end_date', $startDate])
                ->andWhere(['<=', 'group.end_date', $endDate])
                ->sum('total_sum');
            $statistics['clientCertificates'] = ClientCertificate::find()
                ->leftJoin(Group::tableName(), 'group_id=group.id')
                ->where(['>=', 'group.end_date', $startDate])
                ->andWhere(['<=', 'group.end_date', $endDate])
                ->count('client_certificate.id');
            $statistics['clients'] = ClientCertificate::find()
                ->leftJoin(Group::tableName(), 'group_id=group.id')
                ->where(['>=', 'group.end_date', $startDate])
                ->andWhere(['<=', 'group.end_date', $endDate])
                ->select('client_id')
                ->distinct()
                ->count('client_id');
            $statistics['certificateProcessing'] = ClientCertificate::find()
                ->leftJoin(Group::tableName(), 'group_id=group.id')
                ->where(['>=', 'group.end_date', $startDate])
                ->andWhere(['<=', 'group.end_date', $endDate])
                ->andWhere(['number' => null])
                ->count('*');
            $statistics['certificateDone'] = ClientCertificate::find()
                ->leftJoin(Group::tableName(), 'group_id=group.id')
                ->where(['>=', 'group.end_date', $startDate])
                ->andWhere(['<=', 'group.end_date', $endDate])
                ->andWhere(['is not', 'number', null])
                ->count('*');

            if ($toXls) {
                $report = ReportService::byDatesToXls($data);

                $filename = 'report-dates-' . $startDate . '-' . $endDate . '.xls';
                header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
                header('Content-Disposition: attachment;filename="' . $filename . '"');
                header('Cache-Control: max-age=0');

                $writer = new Xls($report);
                $writer->save('php://output');
                exit;
            }
        }

        return $this->render('by_dates', [
            'data' => $data,
            'startDate' => $startDate,
            'endDate' => $endDate,
            'statistics' => $statistics
        ]);
    }

    public function actionByDay()
    {
        $day = Yii::$app->request->post('day');
        $toXls = Yii::$app->request->post('to_xls');

        $data = [];
        $sum = 0;
        if (!empty($day)) {
            $data = ClientCertificate::find()
                ->leftJoin(Client::tableName(), 'client_id=client.id')
                ->where(['date_add' => $day])
                ->andWhere(['paid' => 1])
                ->groupBy('client_id')
                ->select('SUM(total_sum) as total_sum, client.name_ukr, client.surname_ukr, client.patronymic_ukr')
                ->asArray()
                ->all();

            $sum = array_sum(ArrayHelper::getColumn($data, 'total_sum'));

            if ($toXls) {
                $report = ReportService::byDayToXls($data);

                $filename = 'report-day-' . $day . '.xls';
                header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
                header('Content-Disposition: attachment;filename="' . $filename . '"');
                header('Cache-Control: max-age=0');

                $writer = new Xls($report);
                $writer->save('php://output');
                exit;
            }
        }

        return $this->render('by_day', [
            'day' => $day,
            'data' => $data,
            'sum' => $sum,
        ]);
    }

    public function actionStatisticByCourse()
    {
        $startDate = Yii::$app->request->get('start_date');
        $endDate = Yii::$app->request->get('end_date');
        $courseId = Yii::$app->request->get('course_id');

        $query = (new Query())
            ->select("CONCAT_WS(' ', `surname_ukr`, `name_ukr`, `patronymic_ukr`) as name, date_add, date_of_issue, number")
            ->from(ClientCertificate::tableName())
            ->leftJoin(Client::tableName(), 'client.id = client_certificate.client_id');

        $query->where(['paid' => ClientCertificate::STATUS_PAID]);

        if ($startDate) {
            $query->andWhere(['>=', 'date_add', $startDate]);
        }

        if ($endDate) {
            $query->andWhere(['<=', 'date_add', $endDate]);
        }

        if ($courseId) {
            $query->andWhere(['course_id' => $courseId]);
        }

        $certificateData = $query->all();

        return $this->render('statistic_by_course', [
            'certificateData' => $certificateData,
            'startDate' => $startDate,
            'endDate' => $endDate,
        ]);
    }

    public function actionStatistic()
    {
        $startDate = Yii::$app->request->post('start_date');
        $endDate = Yii::$app->request->post('end_date');

        $query = (new Query())
            ->select('
                SUM(client_certificate.total_sum) as total_sum, 
                SUM(case when client_certificate.pay_type = ' . ClientCertificate::PAY_TYPE_CASH . ' then client_certificate.total_sum else 0 end) as total_sum_cash, 
                SUM(case when client_certificate.pay_type = ' . ClientCertificate::PAY_TYPE_BANK_TRANSFER . ' then client_certificate.total_sum else 0 end) as total_sum_bank_transfer,
                COUNT(client_certificate.id) as total_certificates, 
                course.title_ukr as title, course.id as course_id
            ')
            ->from('client_certificate')
            ->leftJoin(Course::tableName(), 'course.id=client_certificate.course_id')
            ->groupBy('course_id');

        $query->where(['paid' => ClientCertificate::STATUS_PAID]);

        $queryConventional = (new Query())
            ->select('
                conventional,
                COUNT(client_certificate.id) AS counter,
                SUM(client_certificate.cost_price) AS total_sum
            ')
            ->from('client_certificate')
            ->leftJoin(Course::tableName(), 'course.id=client_certificate.course_id')
            ->groupBy('conventional');;

        if ($startDate) {
            $query->andWhere(['>=', 'date_add', $startDate]);
            $queryConventional->andWhere(['>=', 'date_add', $startDate]);
        }

        if ($endDate) {
            $query->andWhere(['<=', 'date_add', $endDate]);
            $queryConventional->andWhere(['<=', 'date_add', $endDate]);
        }

        $certificateData = $query->all();
        $conventionalData = $queryConventional->all();

        return $this->render('statistic', [
            'certificateData' => $certificateData,
            'conventionalData' => $conventionalData,
            'startDate' => $startDate,
            'endDate' => $endDate,
        ]);
    }

    public function actionByMiddlemen()
    {
        $query = (new Query())
            ->select('name, sum(total_sum) as total_sum, count(client_certificate.id) as count, middlemen.id as id')
            ->from('middlemen')
            ->leftJoin(ClientCertificate::tableName(), 'middlemen.id=client_certificate.middlemen_id')
            ->groupBy('name, middlemen.id');

        $data = $query->all();

        return $this->render('by_middlemen', [
            'data' => $data,
        ]);
    }

    public function actionPrintCertificates()
    {
        $day = Yii::$app->request->get('day');

        $query = ClientCertificate::find()
            ->with('client', 'course')
            ->orderBy('id DESC');

        if (!empty($day)) {
            $query = $query->where(['date_of_issue' => $day]);
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        return $this->render('print_certificates', [
            'day' => $day,
            'dataProvider' => $dataProvider,
        ]);
    }
}

views/report/by_dates.php
<?php

use app\models\ars\ClientCertificate;
use kartik\date\DatePicker;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\searches\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $certificate ClientCertificate */

$this->title = 'Отчет: по датам';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="report-by_dates">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= Html::beginForm('', 'post', ['id' => 'report-by-dates']) ?>
    <div class="form-group">
        <div class="row">
            <div class="col-lg-3">
                <?= DatePicker::widget(
                    [
                        'name'          => 'start_date',
                        'options'       => ['placeholder' => 'ГГГГ-ММ-ДД', 'autocomplete' => 'off'],
                        'type'          => DatePicker::TYPE_COMPONENT_PREPEND,
                        'value'         => $startDate,
                        'pluginOptions' => [
                            'autoclose' => true,
                            'format'    => 'yyyy-mm-dd',
                        ],
                    ]) ?>
            </div>
            <div class="col-lg-3">
                <?= DatePicker::widget(
                    [
                        'name'          => 'end_date',
                        'options'       => ['placeholder' => 'ГГГГ-ММ-ДД', 'autocomplete' => 'off'],
                        'type'          => DatePicker::TYPE_COMPONENT_PREPEND,
                        'value'         => $endDate,
                        'pluginOptions' => [
                            'autoclose' => true,
                            'format'    => 'yyyy-mm-dd',
                        ],
                    ]) ?>
            </div>
            <?= Html::hiddenInput('to_xls', 0, ['class' => 'toXls'])?>
            <div class="col-lg-1">
                <?= Html::button('Поиск', ['class' => 'report-by-dates btn btn-success']) ?>
            </div>
            <div class="col-lg-1">
                <?= Html::button('В excel', ['class' => 'report-by-dates-to-xls btn btn-info']) ?>
            </div>
        </div>
    </div>
    <?= Html::endForm() ?>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>ФИО</th>
            <th>Дата рождения</th>
            <th>Курс</th>
            <th>Прайс</th>
            <th>Доп. оплата</th>
            <th>Сумма</th>
            <th>Оплечен</th>
            <th>Дата получения</th>
            <th>Посредник</th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($data as $certificate): ?>
            <tr>
                <td><?= $certificate->client->surname_ukr . ' ' . $certificate->client->name_ukr . ' ' . $certificate->client->patronymic_ukr ?></td>
                <td><?= $certificate->client->birthday ?></td>
                <td><?= $certificate->course->title_ukr ?></td>
                <td><?= $certificate->cost_price ?></td>
                <td><?= $certificate->additional_sum ?></td>
                <td><?= $certificate->total_sum ?></td>
                <td><?= $certificate->paid ? 'Да' : 'Нет' ?></td>
                <td><?= $certificate->group->end_date ?></td>
                <td><?= $certificate->middlemen_id ? $certificate->middlemen->name : 'Нет' ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php if (!empty($statistics)): ?>
        <table class="table table-striped table-bordered">
            <tbody>
            <tr>
                <td>Людей</td>
                <td><?= $statistics['clients'] ?></td>
            </tr>
            <tr>
                <td>Сертификатов</td>
                <td><?= $statistics['clientCertificates'] ?></td>
            </tr>
            <tr>
                <td>Сумма</td>
                <td><?= $statistics['totalSum'] ?></td>
            </tr>
            <tr>
                <td>Без номера</td>
                <td><?= $statistics['certificateProcessing'] ?></td>
            </tr>
            <tr>
                <td>С номером</td>
                <td><?= $statistics['certificateDone'] ?></td>
            </tr>
            </tbody>
        </table>
    <?php endif; ?>

    <?php $this->registerJsFile('js/report-by-dates.js', ['depends' => ['yii\web\JqueryAsset']]); ?>
</div>

views/report/by_middlemen.php
<?php


use kartik\date\DatePicker;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Отчет: посредники';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="report-by-middlemen">

    <h1><?= Html::encode($this->title) ?></h1>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>Посредние</th>
            <th>Сертификатов, шт.</th>
            <th>Сумма, грн.</th>
            <th></th>
        </tr>
        </thead>

        <tbody>
        <?php
        $totalCertificates = 0;
        $totalSum = 0;
        ?>
        <?php foreach ($data as $middlemenData): ?>
            <tr>
                <td><?= $middlemenData['name'] ?></td>
                <td><?= $middlemenData['count'] ?></td>
                <td><?= $middlemenData['total_sum'] ?></td>
                <td><?= Html::a('Список', Url::to(['/certificate/list-by-middlemen', 'middlemen_id' => $middlemenData['id']])) ?></td>
            </tr>
        <?php $totalCertificates +=  $middlemenData['count'];?>
        <?php $totalSum +=  $middlemenData['total_sum'];?>
        <?php endforeach; ?>
        <tr>
            <td><b>Всего</b></td>
            <td><?= $totalCertificates ?></td>
            <td><?= $totalSum ?></td>
            <td></td>
        </tr>
        </tbody>
    </table>
</div>

views/report/print_certificates.php
<?php

use app\helpers\AuthHelper;
use app\models\ars\ClientCertificate;
use kartik\date\DatePicker;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\searches\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $certificate ClientCertificate */
/* @var $sum integer */

$this->title = 'Отчет: печать сертификатов';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="report-print_certificates">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= Html::beginForm('', 'get', ['id' => 'report-print-certificates']) ?>
    <div class="form-group">
        <div class="row">
            <div class="col-lg-3">
                <?= DatePicker::widget(
                    [
                        'name' => 'day',
                        'options' => ['placeholder' => 'ГГГГ-ММ-ДД', 'autocomplete' => 'off'],
                        'type' => DatePicker::TYPE_COMPONENT_PREPEND,
                        'value' => $day,
                        'pluginOptions' => [
                            'autoclose' => true,
                            'format' => 'yyyy-mm-dd',
                        ],
                    ]) ?>
            </div>
            <div class="col-lg-1">
                <?= Html::submitButton('Поиск', ['class' => 'report-print_certificates btn btn-success']) ?>
            </div>
        </div>
    </div>
    <?= Html::endForm() ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label' => 'Курс',
                'value' => function ($certificate) {
                    /** @var $certificate ClientCertificate */
                    return $certificate->course->title_ukr;
                }
            ],
            [
                'label' => 'ФИО',
                'format' => 'raw',
                'value' => function ($certificate) {
                    /** @var $certificate ClientCertificate */
                    $text = $certificate->client->getFullNameUkr() . "({$certificate->client->getFullNameTransliteration()})";

                    return Html::a($text, Url::to(['client/view', 'id' => $certificate->client_id]), ['target' => '_blank']);
                }
            ],
            'date_of_issue',
            [
                'attribute' => 'paid',
                'format' => 'boolean'
            ],
            [
                'label' => 'Распечатан',
                'format' => 'raw',
                'value' => function (ClientCertificate $certificate) {
                    return Html::checkbox('printed', $certificate->printed, ['class' => 'form-control ajax-status', 'data-id' => $certificate->id, 'data-attribute' => 'printed',] + (AuthHelper::canEditCertificatePrinted() ? [] : ['disabled' => 'disabled']));
                }
            ],
            [
                'label' => '',
                'format' => 'raw',
                'value' => function ($certificate) {
                    /** @var $model ClientCertificate */
                    $html = Html::a('Печать',
                        ['print/certificate'], [
                            'class' => 'print-button btn btn-success ' . ($certificate->paid ? '' : 'hide'),
                            'target' => '_blank',
                            'data-id' => $certificate->id,
                            'data-method' => 'POST',
                            'data-params' => [
                                'certificate_id' => $certificate->id,
                                'csrf_param' => Yii::$app->request->csrfParam,
                                'csrf_token' => Yii::$app->request->csrfToken,
                            ],
                        ]);

                    $html .= Html::a('Печать на карте',
                        ['print-card/certificate'], [
                            'class' => 'print-button btn btn-success ' . ($certificate->paid ? '' : 'hide'),
                            'target' => '_blank',
                            'data-id' => $certificate->id,
                            'data-method' => 'POST',
                            'data-params' => [
                                'certificate_id' => $certificate->id,
                                'csrf_param' => Yii::$app->request->csrfParam,
                                'csrf_token' => Yii::$app->request->csrfToken,
                            ],
                        ]);
                    if ($certificate->course->has_ukr_only) {
                        $html .= Html::a('Печать укр. шаблона',
                            ['print/certificate'], [
                                'class' => 'print-button btn btn-info ' . ($certificate->paid ? '' : 'hide'),
                                'target' => '_blank',
                                'data-id' => $certificate->id,
                                'data-method' => 'POST',
                                'data-params' => [
                                    'certificate_id' => $certificate->id,
                                    'ukr_only' => 1,
                                    'csrf_param' => Yii::$app->request->csrfParam,
                                    'csrf_token' => Yii::$app->request->csrfToken,
                                ],
                            ]);
                    }
                    return $html;
                }
            ],
        ],
    ]); ?>
</div>

<?php $this->registerJsFile('js/certificate.js', ['depends' => ['yii\web\JqueryAsset']]); ?>

views/report/statistic.php
<?php


use app\models\ars\Course;
use kartik\date\DatePicker;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $startDate string */
/* @var $endDate string */
/* @var $certificateData array */

$this->title = 'Отчет: статистика';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="report-statistic">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= Html::beginForm('', 'post', ['id' => 'report-by-dates']) ?>
    <div class="form-group">
        <div class="row">
            <div class="col-lg-3">
                <?= DatePicker::widget(
                    [
                        'name' => 'start_date',
                        'options' => ['placeholder' => 'ГГГГ-ММ-ДД', 'autocomplete' => 'off'],
                        'type' => DatePicker::TYPE_COMPONENT_PREPEND,
                        'value' => $startDate,
                        'pluginOptions' => [
                            'autoclose' => true,
                            'format' => 'yyyy-mm-dd',
                        ],
                    ]) ?>
            </div>
            <div class="col-lg-3">
                <?= DatePicker::widget(
                    [
                        'name' => 'end_date',
                        'options' => ['placeholder' => 'ГГГГ-ММ-ДД', 'autocomplete' => 'off'],
                        'type' => DatePicker::TYPE_COMPONENT_PREPEND,
                        'value' => $endDate,
                        'pluginOptions' => [
                            'autoclose' => true,
                            'format' => 'yyyy-mm-dd',
                        ],
                    ]) ?>
            </div>
            <div class="col-lg-1">
                <?= Html::submitButton('Поиск', ['class' => 'report-by-dates btn btn-success']) ?>
            </div>
        </div>
    </div>
    <?= Html::endForm() ?>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>Название курса</th>
            <th>Сертификатов, шт.</th>
            <th>Средняя цена, грн.</th>
            <th>Сумма, грн.</th>
            <th>Наличные, грн.</th>
            <th>Безналичный, грн.</th>
        </tr>
        </thead>

        <tbody>
        <?php
        $totalCertificates = 0;
        $totalSum = 0;
        $totalSumCash = 0;
        $totalSumBankTransfer = 0;
        ?>
        <?php foreach ($certificateData as $certificate): ?>
            <tr>
                <td><?= Html::a($certificate['title'], ['report/statistic-by-course', 'start_date' => $startDate, 'end_date' => $endDate, 'course_id' => $certificate['course_id']], ['target' => '_blank']) ?></td>
                <td><?= $certificate['total_certificates'] ?></td>
                <td><?= $certificate['total_sum'] ? number_format($certificate['total_sum'] / $certificate['total_certificates'], 2) : 0 ?></td>
                <td><?= number_format($certificate['total_sum'], 2) ?></td>
                <td><?= number_format($certificate['total_sum_cash'], 2) ?></td>
                <td><?= number_format($certificate['total_sum_bank_transfer'], 2) ?></td>
            </tr>
            <?php $totalCertificates += $certificate['total_certificates']; ?>
            <?php $totalSum += $certificate['total_sum']; ?>
            <?php $totalSumCash += $certificate['total_sum_cash']; ?>
            <?php $totalSumBankTransfer += $certificate['total_sum_bank_transfer']; ?>
        <?php endforeach; ?>
        <tr>
            <td><b>Всего</b></td>
            <td><?= $totalCertificates ?></td>
            <td><?= $totalSum ? number_format($totalSum / $totalCertificates, 2) : 0 ?></td>
            <td><?= number_format($totalSum, 2) ?></td>
            <td><?= number_format($totalSumCash, 2) ?></td>
            <td><?= number_format($totalSumBankTransfer, 2) ?></td>
        </tr>
        </tbody>
    </table>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th></th>
            <th>Сертификатов, шт.</th>
            <th>Сумма, грн.</th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($conventionalData as $conventional): ?>
            <tr>
                <td><?= Course::getConventionalList()[$conventional['conventional']] ?></td>
                <td><?= $conventional['counter'] ?></td>
                <td><?= number_format($conventional['total_sum'], 2) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>


</div>